[package]
name = "rust-ddd-demo"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_add_demo"
path = "src/lib.rs"

[dependencies]
actix-web = "4"
chrono = "0.4"
async-trait = "0.1"
tokio = { version = "1.4", features = ["full"] }
futures = "0.3"
